version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  build-and-test-dev:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install --user -r dev_requirements.txt
          name: Run pip dev_requirements.txt
      # unit test start
      - run:
          command: python ./test/unit_test/ajax/test_ajax_requests.py
          name: Test AJAX Request
      - run:
          command: python ./test/unit_test/api_delete/test_request_delete.py
          name: Test Delete Request
      - run:
          command: python ./test/unit_test/api_get/test_api_get_all_data.py
          name: Test Get All Data
      - run:
          command: python ./test/unit_test/api_get/test_request_get.py
          name: Test GET Method
      - run:
          command: python ./test/unit_test/api_head/test_request_head.py
          name: Test HEAD Method
      - run:
          command: python ./test/unit_test/api_options/test_request_options.py
          name: Test OPTIONS Method
      - run:
          command: python ./test/unit_test/api_patch/test_request_patch.py
          name: Test PATCH Method
      - run:
          command: python ./test/unit_test/api_post/test_request_post.py
          name: Test POST Method
      - run:
          command: python ./test/unit_test/api_put/test_request_put.py
          name: Test PUT Method
      - run:
          command: python ./test/unit_test/api_session/test_request_session.py
          name: Test Session
      - run:
          command: python ./test/unit_test/json/json_reformat_test/test_json_process.py
          name: Test Process Json
      - run:
          command: python ./test/unit_test/json/rw_and_reformat_json_test/rw_and_reformat_json_test.py
          name: Test Read And Write And Reformat Json
      - run:
          command: python ./test/unit_test/generate_report/json_report_test.py
          name: Test Generate Json Report
      - run:
          command: python ./test/unit_test/generate_report/html_report_test.py
          name: Test Generate HTML Report
      - run:
          command: python ./test/unit_test/executor_test/execute_action_test.py
          name: Test Execute Action
      - run:
          command: python ./test/integrated_test/get_dir_file_and_execute/get_dir_file_and_execute.py
          name: Test Get Dir Files And Execute
      - run:
          command: python ./test/unit_test/xml/xml_test.py
          name: Test XML Module
      - run:
          command: python ./test/integrated_test/soap_to_dict_test/soap_to_dict_test.py
          name: Test Soap Data To Dict
      - run:
          command: python ./test/unit_test/generate_report/xml_report_test.py
          name: Test Generate XML Report
      - run:
          command: python ./test/unit_test/soap_test/soap_test.py
          name: Test Get Soap Data
      - run:
          command: python ./test/unit_test/argparse/argparse_test.py
          name: Test Argparse
      - run:
          command: python ./test/unit_test/compare_test/compare_test.py
          name: Test Compare
      - run:
          command: python ./test/unit_test/callback/callback_test.py
          name: Test Callback
      - run:
          command: python ./test/unit_test/create_project/create_project.py
          name: Test Create Project

  build-and-test-stable:
    executor: python/default
    steps:
      - checkout
      # pip require package
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt
      # unit test start
      - run:
          command: python ./test/unit_test/ajax/test_ajax_requests.py
          name: Test AJAX Request
      - run:
          command: python ./test/unit_test/api_delete/test_request_delete.py
          name: Test Delete Request
      - run:
          command: python ./test/unit_test/api_get/test_api_get_all_data.py
          name: Test Get All Data
      - run:
          command: python ./test/unit_test/api_get/test_request_get.py
          name: Test GET Method
      - run:
          command: python ./test/unit_test/api_head/test_request_head.py
          name: Test HEAD Method
      - run:
          command: python ./test/unit_test/api_options/test_request_options.py
          name: Test OPTIONS Method
      - run:
          command: python ./test/unit_test/api_patch/test_request_patch.py
          name: Test PATCH Method
      - run:
          command: python ./test/unit_test/api_post/test_request_post.py
          name: Test POST Method
      - run:
          command: python ./test/unit_test/api_put/test_request_put.py
          name: Test PUT Method
      - run:
          command: python ./test/unit_test/api_session/test_request_session.py
          name: Test Session
      - run:
          command: python ./test/unit_test/json/json_reformat_test/test_json_process.py
          name: Test Process Json
      - run:
          command: python ./test/unit_test/json/rw_and_reformat_json_test/rw_and_reformat_json_test.py
          name: Test Read And Write And Reformat Json
      - run:
          command: python ./test/unit_test/generate_report/json_report_test.py
          name: Test Generate Json Report
      - run:
          command: python ./test/unit_test/generate_report/html_report_test.py
          name: Test Generate HTML Report
      - run:
          command: python ./test/unit_test/executor_test/execute_action_test.py
          name: Test Execute Action
      - run:
          command: python ./test/integrated_test/get_dir_file_and_execute/get_dir_file_and_execute.py
          name: Test Get Dir Files And Execute
      - run:
          command: python ./test/unit_test/xml/xml_test.py
          name: Test XML Module
      - run:
          command: python ./test/integrated_test/soap_to_dict_test/soap_to_dict_test.py
          name: Test Soap Data To Dict
      - run:
          command: python ./test/unit_test/generate_report/xml_report_test.py
          name: Test Generate XML Report
      - run:
          command: python ./test/unit_test/soap_test/soap_test.py
          name: Test Get Soap Data
      - run:
          command: python ./test/unit_test/argparse/argparse_test.py
          name: Test Argparse
      - run:
          command: python ./test/unit_test/compare_test/compare_test.py
          name: Test Compare
      - run:
          command: python ./test/unit_test/callback/callback_test.py
          name: Test Callback
      - run:
          command: python ./test/unit_test/create_project/create_project.py
          name: Test Create Project

workflows:
  main:
    jobs:
      - build-and-test-dev
      - build-and-test-stable:
          requires:
            - build-and-test-dev
