name: APITestka GitHub Actions Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev_requirements.txt
        # unit test start
        # ajax test
      - name: test_ajax_requests
        run: python ./test/unit_test/ajax/test_ajax_requests.py
        # api delete test
      - name: test_request_delete
        run: python ./test/unit_test/api_delete/test_request_delete.py
        # api get test
      - name: test_api_get_all_data
        run: python ./test/unit_test/api_get/test_api_get_all_data.py
      - name: test_request_get
        run: python ./test/unit_test/api_get/test_request_get.py
        # api head test
      - name: test_request_head
        run: python ./test/unit_test/api_head/test_request_head.py
        # api options test
      - name: test_request_options
        run: python ./test/unit_test/api_options/test_request_options.py
      - name: test_request_patch
        run: python ./test/unit_test/api_patch/test_request_patch.py
        # api post test
      - name: test_request_post
        run: python ./test/unit_test/api_post/test_request_post.py
        # api put test
      - name: test_request_put
        run: python ./test/unit_test/api_put/test_request_put.py
        # api session test
      - name: test_request_session
        run: python ./test/unit_test/api_session/test_request_session.py
        # json test
      - name: test_json_process
        run: python ./test/unit_test/json/json_reformat_test/test_json_process.py
      - name: rw_and_reformat_json_test
        run: python ./test/unit_test/json/rw_and_reformat_json_test/rw_and_reformat_json_test.py
        # execute test
      - name: execute_action_test
        run: python ./test/unit_test/executor_test/execute_action_test.py
      - name: get_dir_file_and_execute
        run: python ./test/integrated_test/get_dir_file_and_execute/get_dir_file_and_execute.py
        # xml
      - name: xml_test
        run: python ./test/unit_test/xml/xml_test.py
      - name: soap_to_dict_test
        run: python ./test/integrated_test/soap_to_dict_test/soap_to_dict_test.py
        # soap
      - name: soap_test
        run: python ./test/unit_test/soap_test/soap_test.py
        # argparse
      - name: argparse_test
        run: python ./test/unit_test/argparse/argparse_test.py
        # compare
      - name: compare_test
        run: python ./test/unit_test/compare_test/compare_test.py
